### Test index page
GET http://localhost:8080/Cargo.toml

###
GET http://localhost:8080/fixtures/blake3.txt

### Test static file with tower-http
GET http://localhost:8080/tower/Cargo.toml
# Range: bytes=0-99

###
GET http://localhost:8080/tower/fixtures/blake3.txt

###
GET http://localhost:8080/index.html
Accept: text/html
